USE ROLE ACCOUNTADMIN;

-- Drop solution schemas (preserves shared SF_SOLUTIONS database and warehouse)
DROP SCHEMA IF EXISTS SF_SOLUTIONS.IROPS_CORTEX    CASCADE;
DROP SCHEMA IF EXISTS SF_SOLUTIONS.IROPS_DATA_MART CASCADE;
DROP SCHEMA IF EXISTS SF_SOLUTIONS.IROPS_RAW       CASCADE;

-- Drop scoped analytics role
DROP ROLE IF EXISTS IROPS_OCC_ROLE;
